# Generated by Django 5.0.1 on 2025-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_affiliated_name_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether email has been sent', unique=True),
        ),
    ]
