# Generated by Django 5.0.1 on 2025-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether email has been sent'),
        ),
    ]
